---
# ------------------------------
# Zorg dat Docker aanwezig is
# ------------------------------
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker + Compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# ------------------------------
# Webpagina + Nginx container
# ------------------------------
- name: Copy custom index.html
  ansible.builtin.copy:
    src: index.html    # zoekt automatisch in roles/docker_nginx/files/
    dest: /home/iac/index.html
    mode: '0644'

- name: Run Nginx container with custom page
  community.docker.docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /home/iac/index.html:/usr/share/nginx/html/index.html:ro
