---

#cloud-config
users:
  - name: iac
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

write_files:
  - path: /home/iac/hello.txt
    content: "Hello from Week 06!"
    owner: iac:iac
    permissions: '0644'
    append: false

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /home/iac
  - chown iac:iac /home/iac
  - echo "Hello Week 06 Hybrid Cloud" > /home/iac/hello.txt
  - apt-get update -y
  - apt-get install -y docker.io docker-compose
