---
- name: Week 6 web + azure
  hosts: web,azure
  become: true
  gather_facts: false
  roles:
    - docker_nginx

- name: Week 6 database
  hosts: db
  become: true
  gather_facts: false
  roles:
    - database
