---
- name: Week 6
  hosts: web
  become: true
  gather_facts: false

  tasks:
    - name: Installeer apache2 via shell (niet via apt module)
      ansible.builtin.shell: |
        set -e
        export DEBIAN_FRONTEND=noninteractive
        if ! dpkg -s apache2 >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y apache2
          echo "JUST_INSTALLED"
        else
          echo "ALREADY_PRESENT"
        fi
      register: apache_install
      changed_when: "'JUST_INSTALLED' in apache_install.stdout"

    - name: Copy custom index.html
      copy:
        src: files/index.html
        dest: /home/iac/index.html

    - name: Run Nginx container with custom page
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /home/iac/index.html:/usr/share/nginx/html/index.html

    - name: Controleer of Apache draait
      ansible.builtin.shell: systemctl is-active apache2 || true
      register: apache_state
      changed_when: false
      when: apache_install is defined

    - name: Demonstreer nette fout (block/rescue)
      block:
        - name: Forceer een fout (voorbeeld)
          ansible.builtin.command: /bin/false
      rescue:
        - name: Log foutmelding
          ansible.builtin.debug:
            msg: "Fout bewust veroorzaakt, netjes afgehandeld."

    - name: Toon samenvatting
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Install stdout: {{ apache_install.stdout | default('') }}"
          - "Apache status: {{ apache_state.stdout | default('onbekend') }}"
