#cloud-config
hostname: ubuntu
manage_etc_hosts: true

users:
  - name: Student
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_key}

write_files:
  - path: /etc/systemd/resolved.conf.d/dns.conf
    permissions: "0644"
    content: |
      [Resolve]
      DNS=1.1.1.1 8.8.8.8
      FallbackDNS=8.8.4.4
      DNSStubListener=yes

runcmd:
  # Make sure SSH folder exists
  - mkdir -p /home/Student/.ssh
  - chown Student:Student /home/Student/.ssh
  - chmod 700 /home/Student/.ssh

  # DNS FIX (corrected)
  - mkdir -p /etc/systemd/resolved.conf.d
  - systemctl restart systemd-resolved
  - ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
