#cloud-config
users:
  - name: ${ssh_username}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ${public_key}

write_files:
  - path: /home/iac/hello.txt
    content: "Hello from Week 06!"
    owner: iac:iac
    permissions: '0644'
    append: false

package_update: true
packages:
  - open-vm-tools
  - wget
  - ntpdate
  - docker.io
  - docker-compose

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - mkdir -p /home/iac
  - chown iac:iac /home/iac
  - echo "Hello Week 06 Hybrid Cloud" > /home/iac/hello.txt
  - systemctl enable open-vm-tools
  - systemctl start open-vm-tools

