name: Week 5 CI/CD Pipeline

on:
  push:
    paths:
      - 'ansible/**'
      - '.github/workflows/ci.yml'

jobs:

  syntax-check:
    name: Syntax check
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible syntax check
        run: ansible-playbook --syntax-check ansible/site.yml

  lint:
    name: Lint check
    runs-on: self-hosted
    needs: syntax-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        run: ansible-lint ansible/site.yml || true
        # || true voorkomt dat lint fouten de hele pipeline meteen stoppen

  deploy:
    name: Deploy playbook
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/site.yml



        
        
