---
name: Week 6 CI/CD Pipeline – Full Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  terraform-validate:
    name: Terraform Validate (Azure + ESXi)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Validate Terraform ESXi
        run: |
          cd terraform/esxi
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform Azure
        run: |
          cd terraform/azure
          terraform init -backend=false
          terraform validate

  terraform-deploy:
    name: Terraform Deploy (Azure + ESXi)
    runs-on: self-hosted
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform manually
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
          unzip terraform_1.9.8_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version


      - name: Deploy ESXi VM’s
        run: |
          cd terraform/esxi
          terraform init
          terraform apply -auto-approve

      - name: Deploy Azure VM’s
        run: |
          cd terraform/azure
          terraform init
          terraform apply -auto-approve

      - name: Update inventories (combine IP’s)
        run: |
          chmod +x update_inventories.sh
          ./update_inventories.sh
          echo "✅ Inventory bijgewerkt:"
          cat ansible/inventories/all.ini

  ansible-lint:
    name: Ansible Lint Check
    runs-on: self-hosted
    needs: terraform-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install ansible-lint
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible ansible-lint python3-pip
          ansible-galaxy collection install community.docker
      - name: Run ansible-lint
        run: ansible-lint ansible/

  ansible-deploy:
    name: Ansible Deploy (ESXi + Azure)
    runs-on: self-hosted
    needs: ansible-lint
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible + dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          ansible-galaxy collection install community.docker

      - name: Run full Ansible deployment
        run: |
          ansible-playbook -i ansible/inventories/all.ini ansible/site.yml
