---

name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validate Terraform ESXi
        run: |
          cd terraform/esxi
          terraform init -backend=false
          terraform validate

      - name: Validate Terraform Azure
        run: |
          cd terraform/azure
          terraform init -backend=false
          terraform validate

  update-inventory:
   runs-on: ubuntu-latest
  needs: [terraform]
  steps:
     - uses: actions/checkout@v4
     - name: Update Ansible Inventories
       run: ./update_inventories.sh



  ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible + linters
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible ansible-lint yamllint

      - name: Run Ansible syntax check
        run: ansible-playbook ansible/site.yml --syntax-check

      - name: Run YAML lint
        run: yamllint .

  ansible-deploy:
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Deploy config
        run: ansible-playbook -i ansible/inventory.ini ansible/site.yml

