name: Week 5 - Opdracht 3 Terraform Pipeline

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  validate:
    name: Terraform Validate
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Validate
        run: terraform -chdir=terraform validate

  deploy:
    name: Terraform Apply
    runs-on: self-hosted
    needs: validate
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

  destroy:
    name: Terraform Destroy (manual only)
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve

